name: Python tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test_requirements.txt
      - name: Lint with pylint
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pylint --rcfile .pylintrc ./anastruct
      - name: Run formatting checks
        run: |
          black --check .
      - name: Run type checks
        run: |
          mypy
      - name: Run FEM tests
        run: |
          python ./anastruct/fem/tests/test.py